apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.env.name }}
  labels:
    app: nginx
  
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector: 
    app: nginx

